accounts/urls.py
from django.urls import path
from . import views

# app name: 
app_name = 'accounts'

urlpatterns = [
    path('register/' ,views.register, name='register'),
    path('login/' ,views.login, name='login'),
    path('logout/' ,views.logout, name='logout'),
    path('forgot_password/' ,views.forgotpassword, name='forgot_password'),
    path('change_password/' ,views.change_password, name='change_password'),
    path('dashboard/' ,views.dashboard, name='dashboard'),
    path('user_orders/' ,views.user_orders, name='user_orders'),
    path('user_orders_details/<int:od_id>/' ,views.user_orders_details, name='user_orders_details'),
    path('edit_profile/' ,views.edit_profile, name='edit_profile'),
    path('activate/<uidb64>/<token>/' ,views.activate, name='activate'),
    path('validated_password_reset/<uidb64>/<token>/' ,views.validated_password_reset, name='validated_password_reset'),
    path('reset_password/',views.reset_password, name='reset_password'),  
]

cart_e/urls.py
from django.urls import path
from . import views

# app name: 
app_name = 'cart_e'

urlpatterns = [
    path('' ,views.cart ,name='cart'),
    path('add_cart/<int:product_id>/' ,views.add_cart ,name='add_cart'),
    path('decrement/<int:product_id>/<int:cartItem_id>/' ,views.decrement_cart ,name='decrement_cart'),
    path('remove_cart_item/<int:product_id>/<int:cartItem_id>/' ,views.remove_cart_item ,name='remove_cart_item'),
     path('checkout/' ,views.checkout ,name='checkout'),

]

online_market/urls.py
from django.urls import path
from . import views

# app name: 
app_name = 'online_market'

urlpatterns = [
    path('' ,views.main ,name='main'),
    
]

order/urls.py
from django.urls import path
from . import views



app_name = 'order'


urlpatterns = [
    path('place-order/',views.place_order, name = 'place_order'),
    path('payment/',views.payment, name = 'payment'),
    path('order_complete/',views.order_complete, name = 'order_complete'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('securedadmin/', admin.site.urls),
    path('',include('online_market.urls',namespace='home')),
    path('store/',include('store.urls',namespace='store')),
    path('cart/',include('cart_e.urls',namespace='cart')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('order/',include('order.urls',namespace='order')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views



app_name = 'store'


urlpatterns = [
    path('store',views.store, name = 'store'),
    path('category/<slug:catg_slug>/',views.store, name = 'productByCatg'),
    path('category/<slug:catg_slug>/<slug:product_slug>/',views.product_detail, name = 'product_detail'),
    path('search/',views.search, name = 'search'),
    path('submited_reviews/<int:prt_ID>/',views.submited_reviews, name = 'submitReview'),

]

online_market/models.py
from django.db import models

# Create your models here.

store/models.py
from email.policy import default
from random import choices
from secrets import choice
from unicodedata import category
from django.db import models
from accounts.models import Account, UserProfile
from category.models import Category
from django.utils.text import slugify
from django.db.models import Avg , Count

# Create your models here.

def uploaded_photos(instance , filename):
    imagename , extension = filename.split('.')
    return 'photos/products/%s.%s'%(F'PRODUCT{instance.id}{instance.updated} ',extension)

class Product(models.Model):
    product_name = models.CharField(max_length = 200, unique = True)
    slug = models.SlugField(max_length = 200, unique = True, blank = True)
    description = models.TextField(max_length = 500, blank = True)
    price = models.IntegerField()
    images = models.ImageField(upload_to = uploaded_photos)
    stock = models.IntegerField()
    is_available = models.BooleanField(default = True)
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
  

    

    def save(self,*args,**kwargs):
        self.slug = slugify(self.product_name)
        super(Product,self).save(*args,**kwargs)


    def __str__(self):
        return self.product_name

    def averageReview(self):
        reviews = ReviewRate.objects.filter(product = self, status = True).aggregate(av = Avg('rating'))
        avg = 0
        if reviews['av'] is not None:
            avg = float(reviews['av'])
            return avg

    def countRVid(self):
        reviews = ReviewRate.objects.filter(product = self, status = True).aggregate(count=Count('id'))
        count= None
        if reviews['count'] is not None:
            count = int(reviews['count'])
            return count

class VariationManger(models.Manager):

    def colors(self):
        return super(VariationManger,self).filter(variation_category= 'color',is_active = True)

    def sizes(self):
        return super(VariationManger,self).filter(variation_category= 'size',is_active = True)



variation_category_choice=(
    ('color','color'),
    ('size','size')
)

class Variation(models.Model):
    product = models.ForeignKey(Product,on_delete = models.CASCADE)
    variation_category = models.CharField(max_length = 200 , choices = variation_category_choice)
    variation_value = models.CharField(max_length = 100)
    is_active = models.BooleanField(default = True)
    created = models.DateTimeField(auto_now_add = True)

    objects = VariationManger()

    def __str__(self):
        return self.variation_value


class ReviewRate(models.Model):

    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, blank = True, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100)
    review = models.TextField(max_length=500, blank = True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank = True)
    status = models.BooleanField(default = True)
    updated_at = models.DateTimeField(auto_now = True)
    created_at = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return self.subject


def uploaded_photos(instance , filename):
    imagename , extension = filename.split('.')
    return 'photos/products_gallery/%s.%s'%(f'Pdt_Gellery_{instance.product.updated}' ,extension)

class Product_Gallery(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE) 
    image = models.ImageField(blank=True, upload_to= uploaded_photos, max_length=225) 

    class Meta:
        verbose_name = "Product_Gallery"
        verbose_name_plural = "Product Gallery"
    def __str__(self):
        return self.product.product_name

online_market/views.py
from django.shortcuts import render
from store.models import Product, ReviewRate

# Create your views here.


def main(request):

    products = Product.objects.all().filter(is_available = True).order_by('-created')
    for product in products:
        reviews = ReviewRate.objects.filter(product_id = product.id , status = True)

    context = {
        'products':products,
        'reviews':reviews
    }
    return render(request,'main/home.html',context)

store/views.py
from sre_constants import CATEGORY
from sre_parse import CATEGORIES
from unicodedata import category
from django.http import HttpResponse
from django.shortcuts import  redirect, render, get_object_or_404
from accounts.models import UserProfile
from category.models import Category
from store.models import Product, Product_Gallery
from cart_e.models import CartItem,Cart
from cart_e.views import _cart_id
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from store.models import ReviewRate
from store.form import ReviewForm
from order.models import Product_order
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.

def store(request, catg_slug = None):
    categories = None
    products    = None

    if catg_slug != None:
        categories = get_object_or_404(Category,slug = catg_slug)
        products   = Product.objects.all().filter(category = categories, is_available = True).order_by('-created')
        paginator = Paginator(products, 3)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()
    else:
        products    = Product.objects.all().filter(is_available = True).order_by('-created')
        paginator = Paginator(products, 3)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count() 

    context     = {
        'products':paged_products,
        'product_count':product_count
    }
    return render(request,'store/store.html', context)

def product_detail(request, catg_slug, product_slug):
    
    try:
        product_information = Product.objects.get(category__slug = catg_slug, slug = product_slug)
        is_it_Incart = CartItem.objects.filter(cart__cart_id = _cart_id(request), product = product_information).exists()
        
    except Exception as e:
        raise e
    if request.user.is_authenticated:
        try:
            any_order_there = Product_order.objects.filter(user = request.user , product_id = product_information.id).exists()
        except Product_order.DoesNotExist:
            any_order_there = None
    else:
        any_order_there = None
    
    
    reviews = ReviewRate.objects.filter(product_id = product_information.id , status = True)
   
    product_gallery = Product_Gallery.objects.filter(product_id = product_information.id)
    context = {
        'product_information':product_information,
        'is_it_Incart':is_it_Incart,
        'any_orders_there':any_order_there,
        'reviews':reviews,
        'product_gallery':product_gallery,
        }
    return render(request,'store/product_detail.html',context)


def search(request):
    if request.method == 'GET':
        keyword = request.GET.get('keyword')

        products = Product.objects.filter(
            Q(description__icontains = keyword)|
            Q(product_name__icontains = keyword)
        )
        product_count = products.count()

    return render(request,'store/store.html',{'products':products,'product_count':product_count})


def submited_reviews(request,prt_ID):
    
    if request.method == 'POST':
        url = request.META.get('HTTP_REFERER')
        try:
            reviews = ReviewRate.objects.get(user__id=request.user.id, product__id= prt_ID)
            form = ReviewForm(request.POST , instance=reviews)
            form.save()
            messages.success(request,'Thank you ! Your review has been updated')
            return redirect(url)

        except ReviewRate.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                info = ReviewRate()
                info.subject = form.cleaned_data['subject']
                info.rating = form.cleaned_data['rating']
                info.review = form.cleaned_data['review']
                info.ip =  request.META.get('REMOTE_ADDR')
                info.product_id= prt_ID
                info.user_id = request.user.id
                info.save()
                messages.success(request,'Thank you ! Your review has been submited')
                return redirect(url)
                

online_market/templates/store/cart.html
{% extends 'base.html' %}
{% load static %}


{% block body %}

<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    {% if not cartItems %}
    <h2 class="text-center">Your shoping cart is empty !</h2>
    <br>
    <div class="text-center">
        <a href="{% url 'store:store' %}" class="btn btn-primary" style="background-color: rgb(92, 79, 79); border: none;">Continue shoping</a>
    </div>

    {% else %}
    <div class="row">
        <aside class="col-lg-9">
    <div class="card">
    <table class="table table-borderless table-shopping-cart">
    <thead class="text-muted">
    <tr class="small text-uppercase">
      <th scope="col">Product</th>
      <th scope="col" width="120">Quantity</th>
      <th scope="col" width="120">Price</th>
      <th scope="col" class="text-right" width="200"> </th>
    </tr>
    </thead>
    <tbody>
    {% for item in cartItems %}
    <tr>
        <td>
            <figure class="itemside align-items-center">
                <div class="aside"><img src="{{item.product.images.url}}" class="img-sm"></div>
                <figcaption class="info">
                    <a href="{% url 'store:product_detail' item.product.category.slug item.product.slug %}" class="title text-dark">{{item.product.product_name}}</a>
                    <p class="text-muted small">
                        {%  if item.variations.all  %}
                        {%  for var in item.variations.all  %}
                        {{var.variation_category | lower}}: {{var.variation_value | capfirst}}<br>
                        {%  endfor  %} 
                        {%  endif  %}
                    </p>
                </figcaption>
            </figure>
        </td>
        <td> 
            <!-- col.// -->
                        <div class="col"> 
                            
                            <div class="input-group input-spinner">
                                <div class="input-group-prepend">
                                <a href="{% url 'cart:decrement_cart' item.product.id item.id%}" class="btn btn-light" type="button" id="button-plus"> <i class="fa fa-minus"></i> </a>
                                </div>
                                <input type="text" class="form-control"  value="{{item.quantity}}">
                                <div class="input-group-append">
                                <form action="{% url 'cart:add_cart' item.product.id %}" method="POST">
                                {% csrf_token %}
                                {% for var in item.variations.all %}
                                <input type="hidden" name="{{var.variation_category | lower}}" value="{{var.variation_value | capfirst}}">
                                {% endfor %}
                                <button class="btn btn-light" type="submit" id="button-minus"> <i class="fa fa-plus"></i> </button>
                                </form>
                                </div>

                                
                            </div> <!-- input-group.// -->
                        </div> <!-- col.// -->
        </td>
        <td> 
            <div class="price-wrap"> 
                <var class="price">$ {{item.subTotal}}</var> 
                <small class="text-muted"> $ {{item.product.price}} each </small> 
            </div> <!-- price-wrap .// -->
        </td>
        <td class="text-right"> 
        <a href="{% url 'cart:remove_cart_item' item.product.id item.id %}" class="btn btn-danger"> Remove</a>
        </td>
    </tr>
    {% endfor %}
    </tbody>
    </table>
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <aside class="col-lg-3">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">${{total}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> ${{tax}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-right text-dark b"><strong>${{assembled_total}}</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static 'images/misc/payments.png' %}" height="26">
                </p>
                <a href="{% url 'cart:checkout' %}" class="btn btn-primary btn-block"> Checkout </a>
                <a href="{% url 'store:store' %}" class="btn btn-light btn-block">Continue Shopping</a>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    {% endif %}
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->
    </section>
    

{% endblock %}

online_market/templates/store/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% block body %}

<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
                <article class="gallery-wrap"> 
                    <div class="img-big-wrap mainImage">
                    <center><img src="{{product_information.images.url}}"></center>
                    </div> <!-- img-big-wrap.// -->
                
                    
                </article> <!-- gallery-wrap .end// -->
                        <ul class="thumb">
                            <li>
                                {% for picture in product_gallery %}
                                <a href="{{picture.image.url}}" target="manImage" ><img src="{{picture.image.url}}" alt=""></a>
                                {% endfor %}  
                            </li>
                        </ul>
            </aside>
                <main class="col-md-6 border-left">
            <form action="{% url 'cart:add_cart' product_information.id %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                <article class="content-body">
               
                <h2 class="title">{{product_information.product_name}}</h2>
                {% if reviews %}
                <div class="rate">
                    <span>
                            <li class=" fa fa-star{% if product_information.averageReview >= 0.5 and product_information.averageReview < 1 %}-half-o{% elif product_information.averageReview < 0.5 %}-o{% else %}{% endif %}" aria-hidden ="true"></li>
                            <li class=" fa fa-star{% if product_information.averageReview >= 1.5 and product_information.averageReview < 2 %}-half-o{% elif product_information.averageReview < 1.5 %}-o{% else %}{% endif %}" aria-hidden ="true"></li>
                            <li class=" fa fa-star{% if product_information.averageReview >= 2.5 and product_information.averageReview < 3 %}-half-o{% elif product_information.averageReview < 2.5 %}-o{% else %}{% endif %}" aria-hidden ="true"></li>
                            <li class=" fa fa-star{% if product_information.averageReview >= 3.5 and product_information.averageReview < 4 %}-half-o{% elif product_information.averageReview < 3.5 %}-o{% else %}{% endif %}" aria-hidden ="true"></li>
                            <li class=" fa fa-star{% if product_information.averageReview >= 4.5 and product_information.averageReview < 5 %}-half-o{% elif product_information.averageReview < 4.5 %}-o{% else %}{% endif %}" aria-hidden ="true"></li>
                    </span>
                </div>
                <div><span>{{product_information.countRVid}} reviews</span>  </div>
                {% else %} 
                <div class="rate">
                    <span>
                            <li class=" fa fa-star-o" aria-hidden ="true"></li>
                            <li class=" fa fa-star-o" aria-hidden ="true"></li>
                            <li class=" fa fa-star-o" aria-hidden ="true"></li>
                            <li class=" fa fa-star-o" aria-hidden ="true"></li>
                            <li class=" fa fa-star-o" aria-hidden ="true"></li>
                            
                    </span>
                </div>
                <div><span>No reviews</span>  </div>
                {% endif %} 
                <div class="mb-3">
                    <br> 
                    <var class="price h4">${{product_information.price}}</var> 
                </div> 
                
                <p>{{product_information.description}}</p>
                
                
                <hr>
                    <div class="row">
                        <div class="item-option-select">
                            <h6>Choose Color</h6>
                            <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
                            <label class="btn btn-light">
                                <input type="radio" name="color" value="" disabled selected> Select
                            </label>
                            {% for color in product_information.variation_set.colors %}
                            <label class="btn btn-light">
                                <input type="radio" name="color" value="{{color.variation_value | lower}}"> {{color.variation_value | capfirst}}
                            </label>
                            {% endfor %}
                            </div> 
                        </div>
                        
                    </div> <!-- row.// -->
                    <div class="row">
                        <div class="item-option-select">
                            <h6>Select Size</h6>
                            <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
                            <label class="btn btn-light">
                                <input type="radio" name="size" value="" disabled selected> Select
                            </label>
                            {% for color in product_information.variation_set.sizes %}
                            <label class="btn btn-light">
                                <input type="radio" name="size" value="{{color.variation_value | lower}}"> {{color.variation_value | capfirst}}
                            </label>
                            {% endfor %}
                            </div> 
                        </div>
                    </div>
                    <!-- row.// -->
                    <hr>
                    {% if product_information.stock <= 0 %}
                    <h5>out of stock</h5>
                    <div>
                    <a href="{% url 'store:store' %}" class="btn btn-outline-primary mt-2">Back to store</a>
                    </div>
                    {% else %}
                    <button type="submit" class="btn  btn-primary" style="background-color: rgb(88, 88, 88); border: none;"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
                    {% endif %}
                </article> <!-- product-info-aside .// -->
    </form>   
            </main> <!-- col.// -->
        </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    <br>
    
    <div class="row">
        <div class="col-md-9">
            <form action="{% url 'store:submitReview' product_information.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                    <div>
                        <h5>Write Your Review:</h5>
                        {{product_information.averageReview}}
                        <br>
                            <label>Rate Product:</label>
                            <br>
                            <div class="rate">
                                <input type="radio" name="rating" id = "rating10" value="5" required><label for="rating10" title="5"></label>
                                <input type="radio" name="rating" id = "rating9" value="4.5" required><label for="rating9" title="4.5" class="half"></label>
                                <input type="radio" name="rating" id = "rating8" value="4" required><label for="rating8" title="4"></label>
                                <input type="radio" name="rating" id = "rating7" value="3.5" required><label for="rating7" title="3.5"  class="half"></label>
                                <input type="radio" name="rating" id = "rating6" value="3" required><label for="rating6" title="3"></label>
                                <input type="radio" name="rating" id = "rating5" value="2.5" required><label for="rating5" title="2.5"  class="half"></label>
                                <input type="radio" name="rating" id = "rating4" value="2" required><label for="rating4" title="2"></label>
                                <input type="radio" name="rating" id = "rating3" value="1.5" required><label for="rating3" title="1.5" class="half"></label>
                                <input type="radio" name="rating" id = "rating2" value="1" required><label for="rating2" title="1"></label>
                                <input type="radio" name="rating" id = "rating1" value="0.5" required><label for="rating1" title="0.5" class="half"></label>
                            </div>
                    <br>
                        <p>Title:</p> 
                        <input type="text" class="form-control" name="subject">
                        <br>
                        <p>Review:</p> 
                        <textarea name="review" rows="4" class="form-control"></textarea>
                        <br>
                        {% if user.is_authenticated %}
                            {% if any_orders_there %}
                                <input type="submit" value="Submit Review" class="btn btn-success">
                                {% else %}
                                <p>Buy it first dude</p>
                                {% endif %}
                            {% else %}
                            <p>you should <a href="{% url 'accounts:login' %}">login</a> first</p>
                        {% endif %}
                        {% include 'alerts.html' %}
                    </div><!-- product-info-aside .// -->
            </form>
        
        
        <br>
        <header class="section-heading">
            <h3>Customer Reviews </h3>
            <div class="rate">
                {% if reviews %}
                <span>
                        <li class=" fa fa-star{% if product_information.averageReview >= 0.5 and product_information.averageReview < 1 %}-half-o{% elif product_information.averageReview < 0.5 %}-o{% else %}{% endif %}" aria-hidden ="true"></li>
                        <li class=" fa fa-star{% if product_information.averageReview >= 1.5 and product_information.averageReview < 2 %}-half-o{% elif product_information.averageReview < 1.5 %}-o{% else %}{% endif %}" aria-hidden ="true"></li>
                        <li class=" fa fa-star{% if product_information.averageReview >= 2.5 and product_information.averageReview < 3 %}-half-o{% elif product_information.averageReview < 2.5 %}-o{% else %}{% endif %}" aria-hidden ="true"></li>
                        <li class=" fa fa-star{% if product_information.averageReview >= 3.5 and product_information.averageReview < 4 %}-half-o{% elif product_information.averageReview < 3.5 %}-o{% else %}{% endif %}" aria-hidden ="true"></li>
                        <li class=" fa fa-star{% if product_information.averageReview >= 4.5 and product_information.averageReview < 5 %}-half-o{% elif product_information.averageReview < 4.5 %}-o{% else %}{% endif %}" aria-hidden ="true"></li>
                </span>
                {% else %}
                <span>There is no reviews</span>
                {% endif %}
            </div>  
            
        </header>
        {% for review in reviews %}
        
        <article class="box mb-3">
            <div class="icontext w-100">
                <img src="{{review.profile.profile_image.url}}" class="img-xs icon rounded-circle">
                
                <div class="text">
                    <span class="date text-muted float-md-right">{{review.updated_at | timesince}} ago</span>  
                    <h6 class="mb-1"> {{review.user.full_name}}</h6>
                    
                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <h6>{{review.subject}}</h6>
                <div class="rate">
                    <span>
                        <li class=" fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1.0 %}-o{% else %}{% endif %}" aria-hidden ="true"></li>
                        <li class=" fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2.0 %}-o{% else %}{% endif %}" aria-hidden ="true"></li>
                        <li class=" fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3.0 %}-o{% else %}{% endif %}" aria-hidden ="true"></li>
                        <li class=" fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4.0 %}-o{% else %}{% endif %}" aria-hidden ="true"></li>
                        <li class=" fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5.0 %}-o{% else %}{% endif %}" aria-hidden ="true"></li>
                    </span>
                </div>
                <p>
                    {{review.review}}
                </p>	
            </div>
        </article>
        
        {% endfor %}
    
        
    
        </div> <!-- col.// -->
    </div> <!-- row.// -->
    
    
    </div> <!-- container .//  -->
    </section>
    <script>
        $(document).ready(function(){
            $('.thumb a').click(function(e){
                e.preventDefault();
                $('.mainImage img').attr('src',$(this).attr('href'));
            })
        })
    </script>
{% endblock %}