online_market/urls.py
from django.urls import path
from . import views

# app name: 
app_name = 'online_market'

urlpatterns = [
    path('' ,views.main ,name='main'),
    
]

order/urls.py
from django.urls import path
from . import views



app_name = 'order'


urlpatterns = [
    path('place-order/',views.place_order, name = 'place_order'),
    path('payment/',views.payment, name = 'payment'),
    path('order_complete/',views.order_complete, name = 'order_complete'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('securedadmin/', admin.site.urls),
    path('',include('online_market.urls',namespace='home')),
    path('store/',include('store.urls',namespace='store')),
    path('cart/',include('cart_e.urls',namespace='cart')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('order/',include('order.urls',namespace='order')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views



app_name = 'store'


urlpatterns = [
    path('store',views.store, name = 'store'),
    path('category/<slug:catg_slug>/',views.store, name = 'productByCatg'),
    path('category/<slug:catg_slug>/<slug:product_slug>/',views.product_detail, name = 'product_detail'),
    path('search/',views.search, name = 'search'),
    path('submited_reviews/<int:prt_ID>/',views.submited_reviews, name = 'submitReview'),

]

online_market/models.py
from django.db import models

# Create your models here.

order/models.py
from django.db import models
from accounts.models import Account
from store.models import Product , Variation

# Create your models here.
class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    payment_method = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.payment_id

class Order(models.Model):

    STATUS=(
        ('New','New'),
        ('Accepted','Accepted'),
        ('Completed','Completed'),
        ('Cancelled','Cancelled'),
    )
    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null = True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank = True, null = True)
    order_number = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField(max_length=50)
    address_line1 = models.CharField(max_length=50)
    address_line2 = models.CharField(max_length=50, blank = True)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    order_note = models.CharField(max_length=100, blank = True)
    status = models.CharField(max_length=50 , choices = STATUS, default = 'New')
    order_total = models.FloatField()
    tax = models.FloatField()
    ip = models.CharField(max_length=20, blank = True)
    is_ordered = models.BooleanField(default = False)
    updated_at = models.DateTimeField(auto_now = True)
    created_at = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return self.first_name

    def full_name(self):
        full_name = f'{self.first_name} {self.last_name}'
        return full_name
    
    def full_address(self):
        complete_address = f'{self.address_line1}, {self.address_line2}'
        return complete_address

class Product_order(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank = True, null = True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation = models.ManyToManyField(Variation, blank = True)
    quantity = models.IntegerField()
    product_price = models.FloatField()
    is_ordered = models.BooleanField(default = False)
    updated_at = models.DateTimeField(auto_now = True)
    created_at = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return self.product.product_name

order/forms.py
from django import forms
from order.models import Order


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields =[
            'first_name','last_name','phone_number',
            'email','address_line1','address_line2',
            'city','state','country','order_note'  ,
        ]

online_market/views.py
from django.shortcuts import render
from store.models import Product, ReviewRate

# Create your views here.


def main(request):

    products = Product.objects.all().filter(is_available = True).order_by('-created')
    for product in products:
        reviews = ReviewRate.objects.filter(product_id = product.id , status = True)

    context = {
        'products':products,
        'reviews':reviews
    }
    return render(request,'main/home.html',context)

order/views.py
from django.shortcuts import render , HttpResponse , redirect  
from order.forms import OrderForm
from order.models import Order , Payment, Product_order
from cart_e.models import CartItem
import datetime
from django.http import JsonResponse
from store.models import Product
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
import json

# Create your views here.
# @csrf_protect
def payment(request):
    body = json.loads(request.body)
    
    
    order = Order.objects.get(user = request.user, is_ordered = False, order_number = body['orderID'])
    #  Store Fetched Data From online payment
    payment = Payment(
        user = request.user,
        payment_id = body['transID'],
        payment_method = body['payment_method'],
        amount_paid = order.order_total,
        status = body['status'],

    )
    payment.save()
    order.payment = payment
    order.is_ordered = True
    order.save()

    # Passing cart items to product order:
    cartItems = CartItem.objects.filter(user = request.user)
    
    for item in cartItems:
        product_order = Product_order()
        product_order.order_id = order.id
        product_order.user_id = request.user.id
        product_order.product_id = item.product_id
        product_order.quantity = item.quantity
        product_order.product_price = item.product.price
        product_order.is_ordered = True
        product_order.payment = payment
        product_order.save()

        cartitems = CartItem.objects.get(id = item.id)
        product_variation = cartitems.variations.all()
        product_order = Product_order.objects.get(id = product_order.id)
        product_order.variation.set(product_variation)
        product_order.save()

        # reduce product's stock:
        product  = Product.objects.get(id =item.product_id)
        product.stock -= item.quantity
        product.save()

    #     # clear cart items:

    CartItem.objects.filter(user = request.user).delete()
    user = request.user

        # send email to user that his order has been placed:

    mail_subject = 'Thank you for your order'
    message = render_to_string('orders/order_recieved_email.html',{
                'user': user,
                'order':order,
            })
            # email input:
    to_email = item.user.email
    send_email = EmailMessage(mail_subject,message,to=[to_email])
    send_email.send()

        # Send order number and transID back to senDate function via JsonResponse:
    data={
            'order_number': order.order_number,
            'transID':payment.payment_id

        }

    return JsonResponse(data)



    return render(request,'orders/payment.html')

def place_order(request, total = 0, quantity = 0):
    
    
    current_user = request.user

    cartItems = CartItem.objects.filter(user = current_user)
    ctItems_count = cartItems.count()
    if ctItems_count <= 0:
        return redirect('store:store')
    
    grand_total = 0
    taxs = 0
    for item in cartItems:
        total += (item.product.price * item.quantity)
        quantity += item.quantity
    taxs = (5 * total)* 0.01
    grand_total = total + taxs

    # Store billing information:
    form = OrderForm()
    if request.method == 'POST':
        form = OrderForm(request.POST)

        if form.is_valid():
            data = Order()
            data.user = current_user
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.phone_number = form.cleaned_data['phone_number']
            data.email = form.cleaned_data['email']
            data.address_line1 = form.cleaned_data['address_line1']
            data.address_line2 = form.cleaned_data['address_line2']
            data.city = form.cleaned_data['city']
            data.state = form.cleaned_data['state']
            data.country = form.cleaned_data['country']
            data.order_note = form.cleaned_data['order_note']
            data.order_total = grand_total
            data.tax = taxs
            data.ip = request.META.get('REMOTE_ADDR')
            data.save()
            
            # Generate order number :
            yr = int(datetime.date.today().strftime('%Y'))
            mt = int(datetime.date.today().strftime('%m'))
            dt = int(datetime.date.today().strftime('%d'))
            d = datetime.date(yr, mt, dt)
            current_date = d.strftime('%Y%m%d')
            order_number = f'{current_date}{data.id}'
            data.order_number = order_number
            data.save()
            order = Order.objects.get(user =current_user, order_number = order_number)
            context = {
                'order': order,
                'cartitems': cartItems,
                'total': total,
                'taxs': taxs,
                'grand_total': grand_total
            }
            return render(request,'orders/payment.html', context)
    else:
        # print('not posted')
        return redirect('cart:checkout')

    
    # Order Complete:

def order_complete(request):
    order_number = request.GET.get('order_number')
    transID = request.GET.get('payment_id')

    try:
        order = Order.objects.get(order_number = order_number, is_ordered = True)
        product_ordered = Product_order.objects.filter(order_id = order.id)
        payment = Payment.objects.get(payment_id = transID)

        sub_total = 0

        for i in product_ordered:
            sub_total += i.product_price * i.quantity

        context = {
            'order':order,
            'product_ordered':product_ordered,
            'transID':payment.payment_id,
            'payment': payment,
            'sub_total':sub_total
        }
        return render(request,'orders/order_complete.html',context)
    except (Payment.DoesNotExist, Order.DoesNotExist):

        return redirect('home:main')
    
        

online_market/templates/orders/order_complete.html
{% extends 'base.html' %}
{% load static %}


{% block body %}


<div class="container" style="margin-top: 50px;">
    <center><i class="fas fa-check-circle" style="font-size: 72px;margin-bottom: 20px;color: #28A745;"></i></center>
    <h2 class="text-center">Payment Successful</h2>
	<br>
	<div class="text-center">
		<a href="{% url 'store:store' %}" class="btn btn-success">Shop more</a>
	</div>
</div>

<div class="container" style="margin: 0 auto;width: 50%;padding: 50px;background: #f1f1f1;margin-top: 50px;margin-bottom: 50px;">
    <div class="row invoice row-printable">
        <div class="col-md-12">
            <!-- col-lg-12 start here -->
            <div class="panel panel-default plain" id="dash_0">
                <!-- Start .panel -->
                <div class="panel-body p30">
                    <div class="row">
                        <!-- Start .row -->
                        <div class="col-lg-6">
                            <!-- col-lg-6 start here -->
                            <div class="invoice-logo"><img src="{% static 'images/Uolia1.png' %}" alt="Invoice logo" style="max-height: 40px;"></div>
                        </div>
                        <!-- col-lg-6 end here -->
                        <div class="col-lg-6">
                            <!-- col-lg-6 start here -->
                            <div class="invoice-from">
                                <ul class="list-unstyled text-right">
                                    <li><strong>Invoiced To</strong></li>
                                    <li>{{order.full_name}}</li>
                                    <li>{{order.full_address}}</li>
                                    <li>{{order.city}}, {{order.state}}/li>
                                    <li>{{order.country}}</li>
                                </ul>
                            </div>
                        </div>
                        <!-- col-lg-6 end here -->
                        <div class="col-lg-12">
                            <!-- col-lg-12 start here -->
                            <div class="invoice-details mt25">
                                <div class="well">
                                    <ul class="list-unstyled mb0">
                                        <li><strong>Order</strong> {{order.order_number}}</li>
                                        <li><strong>Transaction</strong> {{transID}}</li>
                                        <li><strong>Order Date:</strong> {{order.created_at}}</li>
                                        <li><strong>Status:</strong> {{order.status}}</li>
                                    </ul>
                                </div>
                            </div>
                           
                            <div class="invoice-items">
                                <div class="table-responsive" style="overflow: hidden; outline: none;" tabindex="0">
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th class="per70 text-center">Description</th>
                                                <th class="per5 text-center">Qty</th>
                                                <th class="per25 text-center">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for item in product_ordered %}
                                            <tr>
                                                <td>{{item.product.product_name}}</td>
                                                <p class="text-muted small">
                                                    {%  if item.variations.all  %}
                                                    {%  for var in item.variation.all  %}
                                                    {{var.variation_category | lower}}: {{var.variation_value | capfirst}}<br>
                                                    {%  endfor  %} 
                                                    {%  endif  %}
                                                </p> 
                                                <td class="text-center">{{item.quantity}}</td>
                                                <td class="text-center">${{item.product_price}} USD</td>
                                            </tr>
                                            {% endfor %}
                                        <tfoot>
                                            <tr>
                                                <th colspan="2" class="text-right">Sub Total:</th>
                                                <th class="text-center">${{sub_total}} USD</th>
                                            </tr>
                                            <tr>
                                                <th colspan="2" class="text-right">Tax:</th>
                                                <th class="text-center">${{order.tax}} USD</th>
                                            </tr>
                                            
                                            <tr>
                                                <th colspan="2" class="text-right">Grand Total:</th>
                                                <th class="text-center">${{order.order_total}} USD</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                            <div class="invoice-footer mt25">
                                <p class="text-center">Thank you for shopping with us!</p>
                            </div>
                        </div>
                        <!-- col-lg-12 end here -->
                    </div>
                    <!-- End .row -->
                </div>
            </div>
            <!-- End .panel -->
        </div>
        <!-- col-lg-12 end here -->
    </div>
    </div>

    


{% endblock %}

online_market/templates/orders/order_recieved_email.html
{% autoescape off %}

Hi {{user.first_name}},

Thank you {{order.user.first_name}} {{order.user.last_name}} for your order.
We will make sure to deliver order {{order.order_number}} as soon as possible.

Mohamed Osman, CEO at Uolia Market
{% endautoescape off %}

online_market/templates/orders/payment.html
{% extends 'base.html' %}
{% load static %}


{% block body %}

<section class="section-content padding-y bg">
    <div class="container">
    
    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="row">
        <aside class="col-lg-8">
          <h4 class="mb-2">Order process and payment:</h4>
            <div class="card mb-3">
                <h5 class="card-header">Billing Address</h5>
                <div class="card-body">
                  <p class="card-text">Order Number: <strong>{{order.order_number}}</strong></p>
                  <p class="card-text">Full Name   : {{order.full_name}}</p>
                  <p class="card-text">Address     : {{order.full_address}}</p>
                  <p class="card-text">City/State  : {%if order.city != order.state%}{{order.city}}, {{order.state}} {% else %}{{order.city}}{% endif %}</p>
                  <p class="card-text">Country     : {{order.country}}</p>
                  <p class="card-text">Contact     : {{order.phone_number}}, {{order.email}}</p>
                  <p class="card-text">{%if order.order_note%}<strong>Order Note</strong>  : {{order.order_note}}{% endif %}</p>
                </div>
              </div>
              <div class="card mb-3">
                <h5 class="card-header">Payment method</h5>
                <div class="card-body">
                  
                  <p class="card-text">Paypal</p>
                </div>
              </div>
              <div class="card">
                <h5 class="card-header">Review product</h5>
                <div class="card-body">
                  <table class="table table-borderless table-shopping-cart">
                    <thead class="text-muted">
                    <tr class="small text-uppercase">
                      <th scope="col">Product</th>
                      <th scope="col" width="120">Quantity</th>
                      <th scope="col" width="120">Price</th>
                      <th scope="col" class="text-right" width="200"> </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for item in cartitems %}
                    <tr>
                        <td>
                            <figure class="itemside align-items-center">
                                <div class="aside"><img src="{{item.product.images.url}}" class="img-sm"></div>
                                <figcaption class="info">
                                    <a href="{% url 'store:product_detail' item.product.category.slug item.product.slug %}" class="title text-dark">{{item.product.product_name}}</a>
                                    <p class="text-muted small">
                                        {%  if item.variations.all  %}
                                        {%  for var in item.variations.all  %}
                                        {{var.variation_category | lower}}: {{var.variation_value | capfirst}}<br>
                                        {%  endfor  %} 
                                        {%  endif  %}
                                    </p>
                                </figcaption>
                            </figure>
                        </td>
                        <td> 
                            <!-- col.// -->
                                        <div class="col"> 
                                            
                                            <div class="input-group input-spinner">
                                            
                                            <label for="quantity" >{{item.quantity}}</label>
                
                                                
                                            </div> <!-- input-group.// -->
                                        </div> <!-- col.// -->
                        </td>
                        <td> 
                            <div class="price-wrap"> 
                                <var class="price">$ {{item.subTotal}}</var> 
                                <small class="text-muted"> $ {{item.product.price}} each </small> 
                            </div> <!-- price-wrap .// -->
                        </td>
                        
                    </tr>
                    {% endfor %}
                    </tbody>
                    </table>
                </div>
              </div>
    
        </aside> <!-- col.// -->
        <aside class="col-lg-4">
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-right">${{total}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Tax:</dt>
                  <dd class="text-right"> ${{taxs}}</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-right text-dark b"><strong>${{grand_total}}</strong></dd>
                </dl>
                <hr>
                <p class="text-center mb-3">
                    <img src="{% static 'images/misc/payments.png' %}" height="26">
                </p>
        
                <!-- Set up a container element for the button -->
                <div id="paypal-button-container"></div>

    <!-- Include the PayPal JavaScript SDK -->
                  <script src="https://www.paypal.com/sdk/js?client-id=AYldN-K-WUGX838v3_e1t2FTdYblyOEokb1C5TP5ehznqDgGvxyX5_V-rdtmSFnIb5f6fLFJ3hMU9o8J&currency=USD"></script>

                  <script>
                      // Render the PayPal button into #paypal-button-container
                      function getCookie(name) {
                                let cookieValue = null;
                                if (document.cookie && document.cookie !== '') {
                                    const cookies = document.cookie.split(';');
                                    for (let i = 0; i < cookies.length; i++) {
                                        const cookie = cookies[i].trim();
                                        // Does this cookie string begin with the name we want?
                                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                            break;
                                        }
                                    }
                                }
                                return cookieValue;
                            }
                      const csrftoken = getCookie('csrftoken');
                      var total = "{{ grand_total }}";
                      var url = "{% url 'order:payment' %}";
                      // var csrftoken = getCookie('csrftoken');
                      var orderID = '{{order.order_number}}';
                      var payment_method = 'PayPal';
                      var redirect_url = "{% url 'order:order_complete' %}"

                      paypal.Buttons({
                                style: {
                                  color:  'silver',
                                  shape:  'pill',
                                  label:  'pay',
                                  height: 40,
                                        },

                          // Set up the transaction
                          createOrder: function(data, actions) {
                              return actions.order.create({
                                  purchase_units: [{
                                      amount: {
                                          value: total,
                                      }
                                  }]
                              });
                          },

                          // Finalize the transaction
                          onApprove: function(data, actions) {
                              return actions.order.capture().then(function(orderData) {
                                  // Successful capture! For demo purposes:
                                  console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                                  var transaction = orderData.purchase_units[0].payments.captures[0];
                                  sendData();
                                  function sendData(){
                                    fetch(url,{
                                      method : 'POST',
                                      headers:{
                                        "Content-type":"application/json",
                                        "X-CSRFToken":csrftoken,

                                      },
                                      body: JSON.stringify({
                                        orderID: orderID,
                                        transID: orderData.id,
                                        payment_method: payment_method,
                                        status:orderData.status,
                                    
                                      }),
                                    })
                                    .then((response) => response.json())
                                    .then((data) => {
                                      console.log('Success', data);
                                      console.log('Transaction completed successfully');
                                      window.location.href = redirect_url + '?order_number='+ data.order_number+'&payment_id='+data.transID
                                  });
                                  }
                                  // alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');

                                  // Replace the above to show a success message within this page, e.g.
                                  // const element = document.getElementById('paypal-button-container');
                                  // element.innerHTML = '';
                                  // element.innerHTML = '<h3>Thank you for your payment!</h3>';
                                  // Or go to another URL:  actions.redirect('thank_you.html');
                              });
                          }


                      }).render('#paypal-button-container');
                  </script>
                
</body>

</html>
                </div>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
    </aside> <!-- col.// -->
    
    
    </div> <!-- row.// -->
    
    <!-- ============================ COMPONENT 1 END .// ================================= -->
    
    </div> <!-- container .//  -->

    </section>
    
    

{% endblock %}