accounts/urls.py
from django.urls import path
from . import views

# app name: 
app_name = 'accounts'

urlpatterns = [
    path('register/' ,views.register, name='register'),
    path('login/' ,views.login, name='login'),
    path('logout/' ,views.logout, name='logout'),
    path('forgot_password/' ,views.forgotpassword, name='forgot_password'),
    path('change_password/' ,views.change_password, name='change_password'),
    path('dashboard/' ,views.dashboard, name='dashboard'),
    path('user_orders/' ,views.user_orders, name='user_orders'),
    path('user_orders_details/<int:od_id>/' ,views.user_orders_details, name='user_orders_details'),
    path('edit_profile/' ,views.edit_profile, name='edit_profile'),
    path('activate/<uidb64>/<token>/' ,views.activate, name='activate'),
    path('validated_password_reset/<uidb64>/<token>/' ,views.validated_password_reset, name='validated_password_reset'),
    path('reset_password/',views.reset_password, name='reset_password'),  
]

cart_e/urls.py
from django.urls import path
from . import views

# app name: 
app_name = 'cart_e'

urlpatterns = [
    path('' ,views.cart ,name='cart'),
    path('add_cart/<int:product_id>/' ,views.add_cart ,name='add_cart'),
    path('decrement/<int:product_id>/<int:cartItem_id>/' ,views.decrement_cart ,name='decrement_cart'),
    path('remove_cart_item/<int:product_id>/<int:cartItem_id>/' ,views.remove_cart_item ,name='remove_cart_item'),
     path('checkout/' ,views.checkout ,name='checkout'),

]

online_market/urls.py
from django.urls import path
from . import views

# app name: 
app_name = 'online_market'

urlpatterns = [
    path('' ,views.main ,name='main'),
    
]

order/urls.py
from django.urls import path
from . import views



app_name = 'order'


urlpatterns = [
    path('place-order/',views.place_order, name = 'place_order'),
    path('payment/',views.payment, name = 'payment'),
    path('order_complete/',views.order_complete, name = 'order_complete'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('securedadmin/', admin.site.urls),
    path('',include('online_market.urls',namespace='home')),
    path('store/',include('store.urls',namespace='store')),
    path('cart/',include('cart_e.urls',namespace='cart')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('order/',include('order.urls',namespace='order')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views



app_name = 'store'


urlpatterns = [
    path('store',views.store, name = 'store'),
    path('category/<slug:catg_slug>/',views.store, name = 'productByCatg'),
    path('category/<slug:catg_slug>/<slug:product_slug>/',views.product_detail, name = 'product_detail'),
    path('search/',views.search, name = 'search'),
    path('submited_reviews/<int:prt_ID>/',views.submited_reviews, name = 'submitReview'),

]

templates/List_Tab.html
<aside class="col-md-3">
    <!--   SIDEBAR   -->
    <ul class="list-group">
        <a class="list-group-item {% if '/dashboard/' in request.path %}active{% endif %}" href="{% url 'accounts:dashboard' %}"> Dashboard </a>
        <a class="list-group-item {% if '/user_orders/' in request.path %}active{% endif %}" href="{% url 'accounts:user_orders' %}"> My Orders </a>
        <a class="list-group-item {% if '/edit_profile/' in request.path %}active{% endif %}" href="{% url 'accounts:edit_profile' %}"> Edit Profile </a>
        <a class="list-group-item {% if '/change_password/' in request.path %}active{% endif %}" href="{% url 'accounts:change_password' %}"> Change Password </a>
    </ul>
    <br>
    <a class="btn btn-light btn-block" href="{% url 'accounts:logout' %}"> <i class="fa fa-power-off"></i> <span class="text">Log out</span> </a> 
    <!--   SIDEBAR .//END   -->
</aside>

templates/alerts.html
{% load static %}
{% if messages %}

    {% for message in messages %}
    <div  id="message" class="container">
    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
        {{ message }}

    </div>
    </div>
    {% endfor %}

{% endif %}

templates/base.html
{%load static%}
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>Uolia | Find Your Stuff With Us</title>

<link href="{% static 'images/fvc.png' %}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>


<!-- Bootstrap4 files-->
<script src="{% static 'js/bootstrap.bundle.min.js' %}" type="text/javascript"></script>
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{% static 'fonts/fontawesome/css/all.min.css' %}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{% static 'css/ui.css'  %}" rel="stylesheet" type="text/css"/>
<link href="{% static 'css/edited.css'  %}" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="{% static 'js/script.js' %}" type="text/javascript"></script>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!-- Include the PayPal JavaScript SDK -->
<!-- <script src="https://www.paypal.com/sdk/js?client-id=AYldN-K-WUGX838v3_e1t2FTdYblyOEokb1C5TP5ehznqDgGvxyX5_V-rdtmSFnIb5f6fLFJ3hMU9o8J&currency=USD"></script> -->
<script type="{% static 'text/javascript' %}">

/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

}); 
// jquery end

setTimeout(function(){
    $('#message').fadeout('slow')
},4000)
</script>


</head>
<body>
    <header class="section-header">
        <!-- navhere -->
        

        <section class="header-main border-bottom">
            <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-2 col-md-3 col-6">
                <a href="{% url 'home:main' %}" class="brand-wrap">
                    <img class="logo" src="{% static 'images/logoo.png' %}">
                </a> <!-- brand-wrap.// -->
            </div>
            <div class="col-lg col-sm col-md col-6 flex-grow-0">
                <div class="category-wrap dropdown d-inline-block float-right">
                    <button type="button" class="btn btn-outline-dark dropdown-toggle" data-toggle="dropdown"> 
                        <i class="fa fa-bars" style="color:rgb(170, 171, 171)"></i> All category 
                    </button>
                    <div class="dropdown-menu">
                        {% for category in links %}
                        <a class="dropdown-item" href="{{ category.get_url }}">{{category}}</a>
                        {% endfor %}
                    </div>
                </div>  <!-- category-wrap.// -->
            </div> <!-- col.// -->
            <a href="{% url 'store:store' %}" class="btn btn-outline-dark">Store</a>
            <div class="col-lg  col-md-6 col-sm-12 col">
                <form method="GET" action="{% url 'store:search' %}" class="search">
                    <div class="input-group w-100">
                        <input type="text" class="form-control" style="width:60%;" name="keyword" placeholder="Search">
                        
                        <div class="input-group-append">
                          <button class="btn btn-outline-dark" type="submit">
                            <i class="fa fa-search"></i>
                          </button>
                        </div>
                    </div>
                </form> <!-- search-wrap .end// -->
            </div> <!-- col.// -->
            <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                        <div class="d-flex justify-content-end mb-3 mb-lg-0">
                            {% if user.is_authenticated %}
                            <div class="widget-header">
                                <small class="title text-muted">Welcome {{user.first_name}}!</small>
                                <div> 
                                    <a href="{% url 'accounts:dashboard' %}">Dashboard</a> <span class="dark-transp"> | </span>
                                    <a href="{% url 'accounts:logout' %}">Logout</a>
                                </div>
                            </div>
                            {% else %}
                            <div class="widget-header">
                                <small class="title text-muted">Go Ahead:</small>
                                <div> 
                                    <a href="{% url 'accounts:login' %}">Sign in</a> <span class="dark-transp"> | </span>
                                    <a href="{% url 'accounts:register' %}"> Register</a>
                                </div>
                            </div>
                            {% endif %}
                            <a href="{% url 'cart:cart' %}" class="widget-header pl-3 ml-3">
                                <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                                <span class="badge badge-pill badge-danger notify">{{count_item}}</span>
                            </a>
                        </div> <!-- widgets-wrap.// -->
                    </div> <!-- col.// -->
        </div> <!-- row.// -->
            </div> <!-- container.// -->
        </section> <!-- header-main .// -->
        
        
        
        
        </header> <!-- section-header.// -->

{% block body %}

<!-- Excute code her -->

{% endblock %}

<!-- ========================= FOOTER ========================= -->
            {% include 'footer.html' %}
<!-- ========================= FOOTER END // ========================= -->

</body>
</html>

templates/footer.html
{%load static%}
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2022 Uolia </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">org3700@gmail.com</span>
				<span  class="px-2">+971565951887</span>
				<span  class="px-2">Green Belt UAQ, UAQ</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>