accounts/urls.py
from django.urls import path
from . import views

# app name: 
app_name = 'accounts'

urlpatterns = [
    path('register/' ,views.register, name='register'),
    path('login/' ,views.login, name='login'),
    path('logout/' ,views.logout, name='logout'),
    path('forgot_password/' ,views.forgotpassword, name='forgot_password'),
    path('change_password/' ,views.change_password, name='change_password'),
    path('dashboard/' ,views.dashboard, name='dashboard'),
    path('user_orders/' ,views.user_orders, name='user_orders'),
    path('user_orders_details/<int:od_id>/' ,views.user_orders_details, name='user_orders_details'),
    path('edit_profile/' ,views.edit_profile, name='edit_profile'),
    path('activate/<uidb64>/<token>/' ,views.activate, name='activate'),
    path('validated_password_reset/<uidb64>/<token>/' ,views.validated_password_reset, name='validated_password_reset'),
    path('reset_password/',views.reset_password, name='reset_password'),  
]

online_market/urls.py
from django.urls import path
from . import views

# app name: 
app_name = 'online_market'

urlpatterns = [
    path('' ,views.main ,name='main'),
    
]

order/urls.py
from django.urls import path
from . import views



app_name = 'order'


urlpatterns = [
    path('place-order/',views.place_order, name = 'place_order'),
    path('payment/',views.payment, name = 'payment'),
    path('order_complete/',views.order_complete, name = 'order_complete'), 
]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('securedadmin/', admin.site.urls),
    path('',include('online_market.urls',namespace='home')),
    path('store/',include('store.urls',namespace='store')),
    path('cart/',include('cart_e.urls',namespace='cart')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('order/',include('order.urls',namespace='order')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_market/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from re import A
from django import forms 
from accounts.models import Account, UserProfile


class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Enter password',
        'class': 'form-control',
    }))

    confirmed_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'confirm password',
        'class': 'form-control',
    }))

    class Meta:
        model = Account
        fields = ['first_name','last_name','email','phone_number']

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        password = cleaned_data.get('password') 
        confirmed_password = cleaned_data.get('confirmed_password') 

        if password != confirmed_password:
            
            raise forms.ValidationError(
                'please check password matching again'
            )



    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs={
                'class': 'form-control',
                'placeholder': f'Enter {field.capitalize()}'
                }

class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'phone_number']

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs={
                'class': 'form-control',
                'placeholder': f'Enter {field.capitalize()}'
                }

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['address_line1', 'address_line2', 'city', 'state', 'country', 'profile_image']

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs={
                'class': 'form-control',
                'placeholder': f'Enter {field.capitalize()}'
                }

accounts/views.py
from django.shortcuts import HttpResponse, get_object_or_404, redirect, render
from accounts.forms import RegisterForm , UserForm, UserProfileForm
from django.contrib import messages ,auth
from accounts.models import Account , UserProfile
from django.contrib.auth.decorators import login_required 

# Verfication emails:
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode , urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage

from cart_e.views import _cart_id
from cart_e.models import Cart , CartItem
from order.models import Order, Product_order
import requests


# Create your views here.

def register(request):
    #  sending data from frontend using forms.
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            password = form.cleaned_data['password']
            username = f'@{first_name}'
        
            # print(first_name , email, phone_number)
            

            # saving data upove in the database

            new_user = Account.objects.create_user(
                first_name = first_name,
                last_name = last_name,
                username = username,
                email = email,
                password = password,

            )

            new_user.phone_number = phone_number
            
            # saving new_user in the database

            new_user.save()

            # User Activation:
            currnet_site = get_current_site(request)
            mail_subject = 'Please activate your account'
            message = render_to_string('accounts/verification_email.html',{
                'user': new_user,
                'domain': currnet_site,
                'uid': urlsafe_base64_encode(force_bytes(new_user.id)),
                'token':default_token_generator.make_token(new_user),
            })
            # email input:
            to_email = email
            send_email = EmailMessage(mail_subject,message,to=[to_email])
            send_email.send()
            # passing submit messages
            messages.success(request,'We have sent to you verification email, please confirm your email')
            return redirect('accounts:register')

    else:
        form = RegisterForm()
    
    context = {
        'form':form
    }
    return render(request,'accounts/register.html',context)

# login functionality

def login(request):
    if request.user.is_authenticated:
        return redirect('home:main')
    else:
        if request.method == 'POST':
            email = request.POST.get('email')
            password = request.POST.get('password')
                # print(email, password)
                # try:
                #     user = Account.objects.get(email = email, password = password)
                # except:
                #     HttpResponse('User not found')

            user = auth.authenticate(email = email, password = password)

            if user is not None:

                try:
                    cart = Cart.objects.get(cart_id = _cart_id(request))
                    is_cart_items_exists = CartItem.objects.filter(cart = cart).exists()
                    if is_cart_items_exists:
                        cartItems = CartItem.objects.filter(cart = cart)

                        # Getting product variations by id
                        product_variations = []

                        for item in cartItems:
                            ex_variations = item.variations.all()
                            product_variations.append(list(ex_variations))

                        # Get CartItem by using user and get It's product variations.
                        cartitems = CartItem.objects.filter(user = user)

                        existing_variations_list = []
                        id_s = []

                        for item in cartitems:
                            existing_variations = item.variations.all()
                            existing_variations_list.append(list(existing_variations))

                            id_s.append(item.id)
                        
                        for attribute in product_variations:
                            if attribute in existing_variations_list:
                                index = existing_variations_list.index(attribute)
                                item_id = id_s[index]
                                item = CartItem.objects.get(id=item_id)
                                item.quantity += 1
                                item.user = user
                                item.save()
                            else:
                                cartitems = CartItem.objects.filter(cart = cart)
                                for item in cartitems:
                                    item.user = user
                                    item.save()

                        # for item in cartItems:
                        #     item.user = user
                        #     item.save()
                except:
                    pass
                auth.login(request, user)
                messages.success(request, 'You are now logged in')
                url = request.META.get('HTTP_REFERER')
                try:
                    query = requests.utils.urlparse(url).query
                    pms = dict(x.split('=') for x in query.split('&'))
                    if 'next' in pms:
                        next_page = pms['next']
                        return redirect(next_page)
                except:   
                    return redirect('accounts:dashboard')
            else:
                messages.error(request, 'Invalid username or password')
                return redirect('accounts:login') 
        
    
    return render(request,'accounts/login.html')

@login_required(login_url='accounts:login')
def logout(request):

    auth.logout(request)
    messages.success(request,'You are logged out')

    
    return redirect('accounts:login')

def activate(request,uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except(TypeError,ValueError,OverflowError,Account.DoesNotExist):
        user =None
    
    if user is not None and default_token_generator.check_token(user,token):
        user.is_active = True
        user.save()
        messages.success(request,'Congratulation your account is activated')
        return redirect('accounts:login')
    else:
        messages.error(request, 'Invalid activation link')
        return redirect('accounts:register')

def forgotpassword(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        if Account.objects.filter(email = email ).exists():
            user = Account.objects.get(email__exact = email)

            
            # User Activation:
            currnet_site = get_current_site(request)
            mail_subject = 'Reset Your Password'
            message = render_to_string('accounts/reset_password_email.html',{
                'user': user,
                'domain': currnet_site,
                'uid': urlsafe_base64_encode(force_bytes(user.id)),
                'token':default_token_generator.make_token(user),
            })
            # email input:
            to_email = email
            send_email = EmailMessage(mail_subject,message,to=[to_email])
            send_email.send()
            # passing submit messages
            messages.success(request,'Password reset email has been sent to your email address !')
            return redirect('accounts:login')

        else:
            messages.error(request,'Account does not exists')
            return redirect('accounts:forgot_password')
    return render(request,'accounts/forgotpassword.html')

def validated_password_reset(request,uidb64, token):
    try:

        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)

    except(TypeError,ValueError,OverflowError,Account.DoesNotExist):
        user =None

    if user is not None and default_token_generator.check_token(user,token):
        request.session['uid'] = uid
        messages.success(request,'Please reset your password ')
        return redirect('accounts:reset_password')
    else:
        messages.erro(request,'This link has been expired')
        return redirect('accounts:login')

def reset_password(request):
    if request.method == 'POST':
        password = request.POST.get('password')
        confirmed_password = request.POST.get('confirmed_password')

        if password == confirmed_password:
            uid = request.session.get('uid')
            user= Account.objects.get(pk = uid)
            user.set_password(password)
            user.save()
            messages.success(request,'New password has been set successfully')
            return redirect('accounts:login')

        else:
            messages.erro(request,'Passwords do not match!')
            return redirect('accounts:reset_password')
    else:
        return render(request,'accounts/reset_password.html')

@login_required(login_url='accounts:login')
def dashboard(request):
    orders = Order.objects.order_by('-created_at').filter(user_id = request.user.id , is_ordered = True)
    counted_orders = orders.count()
    user_profile = UserProfile.objects.get(user = request.user)
    context = {
        'counted_orders': counted_orders,
        'user_profile': user_profile
    }
    return render(request,'accounts/dashboard.html',context)

@login_required(login_url='accounts:login')

online_market/views.py
from django.shortcuts import render
from store.models import Product, ReviewRate

# Create your views here.


def main(request):

    products = Product.objects.all().filter(is_available = True).order_by('-created')
    for product in products:
        reviews = ReviewRate.objects.filter(product_id = product.id , status = True)

    context = {
        'products':products,
        'reviews':reviews
    }
    return render(request,'main/home.html',context)

online_market/templates/accounts/Dashboard.html
{% extends 'base.html' %}
{% load static %}


{% block body %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    {% include 'alerts.html' %}
    <div class="container">
        <div class="row">
        {% include 'List_Tab.html' %}
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Account:</strong>
                <span>{{user.full_name }}</span>
            </header>
            <div class="card-body">
                <div class="row"> 
                   <div class="col-md-6">
                    <div class="card" style="text-align: center;">
                        <div class="card-body">
                            <h5 class="card-title">
                                Total Orders
                            </h5>
                            <h4>{{counted_orders}}</h4>
                            <a href="{% url 'accounts:user_orders' %}">View Orders</a>
                        </div>
                    </div>
                   </div>
                   <div class="col-md-6">
                    <div class="card" style="text-align: center;">
                        <div class="card-body">
                            <img src="{{user_profile.profile_image.url}}" alt="" width="50" height="50" style="border-radius:50%;">
                            <span>
                                <p class="mb-0">{{user.email}}</p>
                                <p>{{user.phone_number}}</p>
                            </span>
                        </div>
                    </div>
                   </div>
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->
            
            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    

{% endblock %}

online_market/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}


{% block body %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    {% include 'alerts.html' %}
    <div class="container">
        <div class="row">
        {% include 'List_Tab.html' %}
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Change Password:</strong>
            </header>
            <div class="card-body">
               
                <div class="row"> 
                   <div class="col-md-12">
                        <form action="{% url 'accounts:change_password' %}" method="POST">
                            {% csrf_token %}
                                    <div class="form-group">
                                        <label for="current_password">Current Password</label>
                                        <input type="password" name="current_password" placeholder="Current Password" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="current_password">Create New Password</label>
                                        <input type="password" name="create_new_password" placeholder="Create New Password" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label for="current_password">Confirm New Password</label>
                                        <input type="password" name="confirm_new_password" placeholder="Confirm New Password" class="form-control">
                                    </div> 
                                <input type="submit" value="Save" class="btn btn-primary">
                        </form>
                   </div>
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->
            
            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    



{% endblock %}

online_market/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}


{% block body %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    {% include 'alerts.html' %}
    <div class="container">
        <div class="row">
        {% include 'List_Tab.html' %}
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Edit Profile:</strong>
            </header>
            <div class="card-body">
                <div class="text-center mb-3 ">
                    <img src="{{user_profile.profile_image.url}}" alt="Not Found" width="100" style="border-radius: 50%; border: 2px solid black;" class="mb-2">
                    <h3 style="color: rgb(0, 117, 164);">{{ user.full_name }}</h3>
                </div>
                <div class="row"> 
                   <div class="col-md-12">
                        <form action="{% url 'accounts:edit_profile' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="">First Name</label>
                                    {{user_form.first_name}}
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="">Last Name</label>
                                    {{user_form.last_name}}
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="">Phone Number</label>
                                    {{user_form.phone_number}}
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="">Profile Picture</label>
                                    {{profile_form.profile_image}}
                                </div>
                                <div class="form-row">
                                    <div class="form-group col-md-6">
                                        <label for="">Address Line 1</label>
                                        {{profile_form.address_line1}}
                                    </div>
                                    <div class="form-group col-md-6">
                                        <label for="">Address Line 2</label>
                                        {{profile_form.address_line2}}
                                    </div>
                                    <div class="form-row">
                                        <div class="form-group col-md-4">
                                            <label for="">City</label>
                                            {{profile_form.city}}
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label for="">State</label>
                                            {{profile_form.state}}
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label for="">Country</label>
                                            {{profile_form.country}}
                                        </div>
                                        <input type="submit" value="Save" class="btn btn-primary">
                                    </div>
                                </div>
                            </div>
                        </form>
                   </div>
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->
            
            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    



{% endblock %}

online_market/templates/accounts/forgotpassword.html
{% extends 'base.html' %}
{% load static %}


{% block body %}


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
        <div class="card mx-auto" style="max-width: 600px; margin-top:100px;">
          <div class="card-body">
          <h4 class="card-title mb-4">Forgot password</h4>
          <form method="POST" action="">
            {% csrf_token %}
              <div class="form-group">
                 <input type="email" class="form-control" name="email" placeholder="Email Address" >
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="#" class="float-right">Forgot password?</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Submit  </button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="#">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    


{% endblock %}

online_market/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}


{% block body %}


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
            {% if user.is_authenticated %}
            <!-- {% include 'alerts.html' %} -->
            {% else %}
            {% include 'alerts.html' %}
            {% endif %}
          <h4 class="card-title mb-4">Sign in</h4>
          <form method="POST" action="">
            {% csrf_token %}
              <div class="form-group">
                 <input type="email" class="form-control" name="email" placeholder="Email Address" >
              </div> <!-- form-group// -->
              <div class="form-group">
                <input type="password" name="password" class="form-control" placeholder="Password" >
              </div> <!-- form-group// -->
              
              <div class="form-group">
                  <a href="{% url 'accounts:forgot_password' %}" class="float-right">Forgot password?</a> 
               
              </div> <!-- form-group form-check .// -->
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Login  </button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="#">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    


{% endblock %}

online_market/templates/accounts/reset_password.html
{% extends 'base.html' %}
{% load static %}


{% block body %}


<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">

    <!-- ============================ COMPONENT LOGIN   ================================= -->
        <div class="card mx-auto" style="max-width: 380px; margin-top:100px;">
          <div class="card-body">
            {% if user.is_authenticated %}
            <!-- {% include 'alerts.html' %} -->
            {% else %}
            {% include 'alerts.html' %}
            {% endif %}
          <h4 class="card-title mb-4">Set new password</h4>
          <form method="POST" action="{% url 'accounts:reset_password' %}">
            {% csrf_token %}
              <div class="form-group">
                 <input type="password" class="form-control" name="password" placeholder="password" >
              </div> <!-- form-group// -->
              <div class="form-group">
                <input type="password" name="confirmed_password" class="form-control" placeholder="confirm password" >
              </div> <!-- form-group// -->
              
              
              <div class="form-group">
                  <button type="submit" class="btn btn-primary btn-block"> Set New Password  </button>
              </div> <!-- form-group// -->    
          </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         <p class="text-center mt-4">Don't have account? <a href="#">Sign up</a></p>
         <br><br>
    <!-- ============================ COMPONENT LOGIN  END.// ================================= -->
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    


{% endblock %}

online_market/templates/accounts/reset_password_email.html
{% autoescape off %}

Hi {{user.first_name}},

As requirded, please click on link below to rest your  password:
http://{{domain}}{% url 'accounts:validated_password_reset' uidb64=uid token=token %}

If you think that was not you, please ignore this email.

{% endautoescape off %}

online_market/templates/accounts/user_orders.html
{% extends 'base.html' %}
{% load static %}


{% block body %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    {% include 'alerts.html' %}
    <div class="container">
        <div class="row">
        {% include 'List_Tab.html' %}
        <main class="col-md-9">
            <article class="card">
            <header class="card-header">
                <strong class="d-inline-block mr-3">Orders History:</strong>
            </header>
            <div class="card-body">
                <div class="row"> 
                   <div class="col-md-12">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Order</th>
                                <th scope="col">Billin Name</th>
                                <th scope="col">Phone/Mobile</th>
                                <th scope="col">Total orders</th>
                                <th scope="col">Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in orders %}
                            <tr>
                                <th scope="row"><a href="{% url 'accounts:user_orders_details' order.order_number %}">{{order.order_number}}</a></th>
                                <td>{{order.full_name}}</td>
                                <td>{{order.phone_number}}</td>
                                <td>{{order.order_total}}</td>
                                <td>{{order.created_at}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                   </div>
                </div> <!-- row.// -->
            </div> <!-- card-body .// -->
            
            </article> <!-- order-group.// --> 
        </main>
    </div> <!-- row.// -->
    </div>
    
    
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    



{% endblock %}

online_market/templates/accounts/verification_email.html
{% autoescape off %}

Hi {{user.first_name}},

Please in the link below to confirm your registration
http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token %}

If you think that was not you, please ignore this email.

{% endautoescape off %}